### ISSUE TITLE
`file` throws warning when downloading file over https in master-less setup

### ISSUE THREAD

**Issue by skrivy** [puppetlabs/puppet#9336] opened 2024-05-07 15:56 UTC
## Describe the Bug

When downloading external resources via file in a master-less environment, puppet throws warnings as it is missing agent ssl files.

```
root@node:~  # /opt/puppetlabs/bin/puppet apply init.pp
Notice: Compiled catalog for node in environment production in 0.01 seconds
Warning: Private key for 'node' does not exist
Warning: Client certificate for 'node' does not exist
Notice: /Stage[main]/Main/File[/tmp/file]/ensure: defined content as '{mtime}2023-09-25 06:36:57 UTC'
Notice: Applied catalog in 0.10 seconds
```

## Expected Behavior

No warning being thrown when downloading external resources over https.

```
root@node:~  # /opt/puppetlabs/bin/puppet apply init.pp
Notice: Compiled catalog for node in environment production in 0.01 seconds
Notice: /Stage[main]/Main/File[/tmp/file]/ensure: defined content as '{mtime}2023-09-25 06:36:57 UTC'
Notice: Applied catalog in 0.10 seconds
```

## Steps to Reproduce

1. Install clean Debian 12
2. `wget https://apt.puppetlabs.com/puppet8-release-bookworm.deb`
3. `dpkg -i puppet8-release-bookworm.deb`
4. `apt-get update`
5. `apt-get install puppet-agent`
6. Create file `init.pp` with following content:
```
file { '/tmp/file':
  source => 'https://artifacts.elastic.co/GPG-KEY-elasticsearch',
}
```
7. `/opt/puppetlabs/bin/puppet apply init.pp`

## Environment
 - Version: 8.6.0-1bookworm
 - Platform Debian 12.5

## Additional Context

We found this issue when we tried to download apt key (via apt::keyring) over https from external source. There is no issue when downloading over insecure http.

**Comment by joshcooper** [comment] 2024-05-07 16:41
This is a duplicate of https://github.com/puppetlabs/puppet/issues/9248, closing.

**Closed by joshcooper** 2024-05-07 16:41 UTC
Labels: bug
